package com.maze.domain;

import java.util.Objects;

/**
 * Wrapper for coordinates so don't have to use verbose AbstractMap.SimpleEntry.
 */
public class Coordinates {
    private final int y;
    private final int x;

    /**
     * Creates a new coordinate objects. Note that y is given before x.
     * @param y
     * @param x
     */
    public Coordinates(int y, int x) {
        this.x = x;
        this.y = y;
    }

    public int getY() {
        return y;
    }

    public int getX() {
        return x;
    }

    // Below method generated by IntelliJ

    @Override
    public String toString() {
        return "Coordinates{" +
                "y=" + y +
                ", x=" + x +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Coordinates that = (Coordinates) o;
        return getY() == that.getY() && getX() == that.getX();
    }

    @Override
    public int hashCode() {
        return Objects.hash(getY(), getX());
    }
}
