package com.maze;

import java.util.Objects;

/**
 * Wrapper for coordinates so dont have to use verbose AbstractMap.SimpleEntry.
 * Maybe could also use Apache Commons Pair-class later.
 */
public class Coordinates {
    private final int x;
    private final int y;

    public Coordinates(int x, int y) {
        this.x = x;
        this.y = y;
    }

    public int getX() {
        return x;
    }

    public int getY() {
        return y;
    }

    @Override
    public boolean equals(Object o) {
        // Generated by IntelliJ, not my own code style
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Coordinates that = (Coordinates) o;
        return getX() == that.getX() && getY() == that.getY();
    }
}
